// data source: https://www.cbinsights.com/research-unicorn-companies

var csvData = {
    countryCategories: [
        [1,'Australia','Collaboration & Project Management'],
        [2,'Brazil','Fintech'],
        [1,'Canada','Social'],
        [1,'China','Adtech'],
        [1,'China','AI / Facial Recognition'],
        [5,'China','AutoTech'],
        [1,'China','Chips & Semiconductors'],
        [2,'China','Clothing & Accessories'],
        [3.84,'China','Computer Vision/ AI'],
        [1,'China','Cybersecurity'],
        [11,'China','Digital Media'],
        [57.25,'China','eCommerce/Marketplace'],
        [5.5,'China','Ed Tech'],
        [1,'China','Facilities'],
        [22.56,'China','Fintech'],
        [2.8,'China','Food & Grocery'],
        [63.58,'China','Hardware'],
        [7.5,'China','Healthcare'],
        [1,'China','HR & Workforce Management'],
        [1.51,'China','Internet Software & Services'],
        [5 ,'China','Internet Software & Services'],
        [1,'China','Mobile Software & Services'],
        [69.1,'China','On-Demand'],
        [4.1,'China','Real Estate'],
        [5.7,'China','Retail'],
        [1,'China','Robotics'],
        [5,'China','Social'],
        [1,'China','Supplychain/ logistics'],
        [1.15,'Colombia','Business Products & Services'],
        [1,'Czech Republic','Cybersecurity'],
        [1.1,'France','Big Data'],
        [1.6,'France','On-Demand'],
        [3.54,'Germany','eCommerce/Marketplace'],
        [5.15,'Germany','Healthcare'],
        [2.2,'Germany','Management & Strategy Consulting'],
        [1,'India','Adtech'],
        [20.7,'India','eCommerce/Marketplace'],
        [2,'India','Energy & Utilities'],
        [5.7,'India','Fintech'],
        [3.65,'India','On-demand'],
        [2.4,'India','Social'],
        [1.8,'Indonesia','On-Demand'],
        [2,'Indonesia','TravelTech'],
        [1,'Israel','Consumer Electronics'],
        [1.6,'Israel','Hardware'],
        [1.5,'Israel','Mobile Software & Services'],
        [1,'Japan','eCommerce/Marketplace'],
        [1.1,'Luxembourg','eCommerce/Marketplace'],
        [2.5,'Malta','On-demand'],
        [1,'Netherlands','eCommerce/Marketplace'],
        [2.3,'Netherlands','Fintech'],
        [1.04,'Nigeria','eCommerce/Marketplace'],
        [6,'Singapore','On-Demand'],
        [1.58,'South Africa','Food and Beverage'],
        [1,'South Africa','Telecommunications'],
        [1.78,'South Korea','Beauty & grooming'],
        [5,'South Korea','eCommerce/Marketplace'],
        [4,'South Korea','Mobile Software & Services'],
        [2.5,'Sweden','Fintech'],
        [8.53,'Sweden','Internet Software & Services'],
        [1.01,'Switzerland','Fintech'],
        [1,'Switzerland','VR/AR'],
        [1.2,'United Arab Emirates','On Demand'],
        [1,'United Kingdom','AR/VR'],
        [6.02,'United Kingdom','Computer Hardware & Services'],
        [4.75,'United Kingdom','eCommerce/Marketplace'],
        [6.8,'United Kingdom','Fintech'],
        [1.15,'United Kingdom','Food & Beverages'],
        [2.55,'United Kingdom','Healthcare'],
        [1.07,'United Kingdom','Internet Software & Services'],
        [2,'United Kingdom','On-demand'],
        [1,'United States','3D Printing'],
        [2.6,'United States','Adtech'],
        [3.14,'United States','Auto Tech'],
        [31.9,'United States','Big Data'],
        [2.4,'United States','Biotechnology'],
        [1,'United States','Cannabis'],
        [1,'United States','Cleantech'],
        [2,'United States','Clothing & Accessories'],
        [2,'United States','Construction Tech'],
        [10.92,'United States','Cybsersecurity'],
        [1.19,'United States','Digital Health'],
        [1,'United States','Digital Media'],
        [46.4,'United States','eCommerce/Marketplace'],
        [1,'United States','Ed Tech'],
        [1.5,'United States','Entertainment'],
        [20,'United States','Facilities'],
        [38.69,'United States','Fintech'],
        [1.3,'United States','Fitness'],
        [1.4,'United States','Food Delivery'],
        [2.6,'United States','Gaming'],
        [2.46,'United States','Genomics'],
        [2.7,'United States','Greentech'],
        [1.7,'United States','Hardware'],
        [24,'United States','Healthcare'],
        [56.3,'United States','Internet Software & Services'],
        [1.4,'United States','IoT'],
        [8.4,'United States','Media'],
        [83.7,'United States','On-Demand'],
        [21.5,'United States','Other Transportation'],
        [3.2,'United States','Real Estate'],
        [1.1,'United States','Robotic Process Automation'],
        [16.7,'United States','Social'],
        [1,'United States','SpaceTech'],
        [1.5,'United States','TravelTech'],
        [4.98,'United States','VR/AR']
    ],
data: { Australia: 
   [ { name: 'Canva',
       val: '1.00',
       date: '1/8/18',
       country: 'Australia',
       category: 'Collaboration & Project Management',
       investors: '"Sequoia Capital China,  Blackbird Ventures,  Matrix Partners"' } ],
  Brazil: 
   [ { name: 'Nubank',
       val: '2.00',
       date: '3/1/18',
       country: 'Brazil',
       category: 'Fintech',
       investors: '"Sequoia Capital,  Redpoint e.ventures,  Kaszek Ventures"' } ],
  Canada: 
   [ { name: 'Kik Interactive',
       val: '1.00',
       date: '8/18/15',
       country: 'Canada',
       category: 'Social',
       investors: '"Union Square Ventures,  RRE Ventures,  Spark Capital"' } ],
  China: 
   [ { name: 'Panshi',
       val: '1.00',
       date: '5/5/15',
       country: 'China',
       category: 'Adtech',
       investors: '"WI Harper Group,  Fang Fund Partners,  NewMarging Ventures"' },
     { name: 'Face++ (Megvii)',
       val: '1.00',
       date: '10/31/17',
       country: 'China',
       category: 'AI / Facial Recognition',
       investors: '"Ant Financial Services Group,  Russia-China Investment Fund,  Foxconn Technology Company"' },
     { name: 'NIO',
       val: '5.00',
       date: '3/15/17',
       country: 'China',
       category: 'AutoTech',
       investors: '"Baidu Venture Capital,  Capital Today,  GIC"' },
     { name: 'Cambricon',
       val: '1.00',
       date: '8/18/17',
       country: 'China',
       category: 'Chips & Semiconductors',
       investors: '"Alibaba Entrepreneurs Fund,  CAS Investment Management Co.,  Lenovo Ventures Group"' },
     { name: 'Trendy Group International',
       val: '2.00',
       date: '2/13/12',
       country: 'China',
       category: 'Clothing & Accessories',
       investors: 'L Capital Partners' },
     { name: 'YITU Technology',
       val: '2.37',
       date: '3/8/18',
       country: 'China',
       category: 'Computer Vision',
       investors: '"Sequoia Capital China,  Banyan Capital"' },
     { name: 'SenseTime',
       val: '1.47',
       date: '7/11/17',
       country: 'China',
       category: 'Computer Vision/ AI',
       investors: '"Star VC,  IDG Capital,  Infore Capital"' },
     { name: 'Tongdun Technology',
       val: '1.00',
       date: '10/10/17',
       country: 'China',
       category: 'Cybersecurity',
       investors: '"Advantech Capital,  Temasek Holdings Ltd.,  Tiantu Capital Co."' },
     { name: 'Toutiao',
       val: '11.00',
       date: '4/7/17',
       country: 'China',
       category: 'Digital Media',
       investors: '"Sequoia Capital China,  SIG Asia Investments,  Sina Weibo"' },
     { name: 'Pindouduo',
       val: '1.50',
       date: '7/20/16',
       country: 'China',
       category: 'eCommerce',
       investors: '"Tencent Holdings,  Banyan Capital,  Cathay Innovation"' },
     { name: 'Dada',
       val: '1.00',
       date: '12/31/15',
       country: 'China',
       category: 'eCommerce',
       investors: '"Sequoia Capital China,  DST,  Greenwoods Asset Management"' },
     { name: 'China Internet Plus Holding (Meituan Dianping)',
       val: '30.00',
       date: '12/22/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"DST Global,  Trustbridge Partners,  Capital Today"' },
     { name: 'Lianjia',
       val: '5.80',
       date: '4/8/16',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Tencent,  Baidu,  Huasheng Capital"' },
     { name: 'Maoyan-Weiying',
       val: '3.00',
       date: '11/10/17',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Tencent Holdings,  Enlight Media Group"' },
     { name: 'VANCL',
       val: '3.00',
       date: '12/14/10',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Ceyuan Ventures,  QiMing Venture Partners,  Temasek Holdings"' },
     { name: 'Weiying',
       val: '2.00',
       date: '11/17/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Tencent,  iDreamSky Technology,  GGV Capital"' },
     { name: 'Tujia',
       val: '1.50',
       date: '6/17/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"GGV Capital,  QiMing Venture Partnersl"' },
     { name: 'Koudai Gouwu',
       val: '1.40',
       date: '10/23/14',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"New Enterprise Associates,  Tiger Global management,  Tencent"' },
     { name: 'Jiuxian',
       val: '1.05',
       date: '7/30/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Sequoia Capital China,  Rich Land Capital,  Merrysunny Wealth"' },
     { name: 'Fanli',
       val: '1.00',
       date: '4/20/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"QiMing Venture Partners,  Steam boat Ventures"' },
     { name: 'BeiBei',
       val: '1.00',
       date: '1/22/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Banyan Capital,  New Horizon Capital,  IDG Capital Partners"' },
     { name: 'Zhaogang',
       val: '1.00',
       date: '6/29/17',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"K2 Ventures,  Matrix Partners China,  IDG Capital"' },
     { name: 'Mia.com',
       val: '1.00',
       date: '9/8/15',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Sequoia Capital China,  ZhenFund,  K2 Ventures"' },
     { name: 'Xiaohongshu',
       val: '1.00',
       date: '3/31/16',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"GGV Capital,  ZhenFund,  Tencent"' },
     { name: 'Guazi',
       val: '1.00',
       date: '3/12/16',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Sequoia Capital China,  GX Capital"' },
     { name: 'XiaoZhu',
       val: '1.00',
       date: '11/1/17',
       country: 'China',
       category: 'eCommerce/Marketplace',
       investors: '"Morningside Ventures,  Capital Today,  JOY Capital"' },
     { name: 'iTutorGroup',
       val: '1.00',
       date: '11/18/15',
       country: 'China',
       category: 'Ed Tech',
       investors: '"QiMing Venture Partners,  Temasek Holdings,  Silverlink Capital"' },
     { name: 'Vipkid',
       val: '1.50',
       date: '8/23/17',
       country: 'China',
       category: 'Edtech',
       investors: '"Sequoia Capital China,  Tencent Holdings,  Sinovation Ventures"' },
     { name: 'Yuanfudao',
       val: '1.00',
       date: '5/31/17',
       country: 'China',
       category: 'Edtech',
       investors: '"Tencent Holdings,  Warbug Pincus,  IDG Capital"' },
     { name: 'HuJiang',
       val: '1.00',
       date: '10/29/15',
       country: 'China',
       category: 'Edtech',
       investors: '"China Minsheng Investment,  Baidu,  Wanxin Media"' },
     { name: '17zuoye',
       val: '1.00',
       date: '3/7/18',
       country: 'China',
       category: 'EdTech',
       investors: '"DST Global,  Temasek Holdings"' },
     { name: 'Mofang Gongyu',
       val: '1.00',
       date: '4/13/16',
       country: 'China',
       category: 'Facilities',
       investors: '"Warburg Pincus,  Aviation Industry Corporation of China"' },
     { name: 'Lu.com',
       val: '18.50',
       date: '12/26/14',
       country: 'China',
       category: 'Fintech',
       investors: '"Ping An Insurance CDH Investments,  Bank of China"' },
     { name: 'LaKala',
       val: '1.60',
       date: '6/23/15',
       country: 'China',
       category: 'Fintech',
       investors: '"China Continent Property & Casualty Insurance,  China Renaissance Capital Investment,  China Taiping Life Insurance"' },
     { name: 'Tuandaiwang',
       val: '1.46',
       date: '5/30/17',
       country: 'China',
       category: 'Fintech',
       investors: '"Beihai Hongtai Investment,  China Minsheng Investment,  Yisheng Innovation"' },
     { name: '51Xinyongka',
       val: '1.00',
       date: '9/21/16',
       country: 'China',
       category: 'Fintech',
       investors: '"GGV Capital,  JD.com,  Meridian Capital China"' },
     { name: 'Meicai',
       val: '2.80',
       date: '1/11/18',
       country: 'China',
       category: 'Food & Grocery',
       investors: '"Tiger Global Management,  Blue Lake Capital,  ZhenFund"' },
     { name: 'Xiaomi',
       val: '46.00',
       date: '12/21/11',
       country: 'China',
       category: 'Hardware',
       investors: '"Digital Sky Technologies,  QiMing Venture Partners,  Qualcomm Ventures"' },
     { name: 'DJI Innovations',
       val: '10.00',
       date: '5/6/15',
       country: 'China',
       category: 'Hardware',
       investors: '"Accel Partners,  Sequoia Capital"' },
     { name: 'Meizu Technology',
       val: '4.58',
       date: '7/23/14',
       country: 'China',
       category: 'Hardware',
       investors: '"Telling Telecommunication Holding Co.,  Alibaba Group"' },
     { name: 'Royole Corporation',
       val: '3.00',
       date: '11/4/16',
       country: 'China',
       category: 'Hardware',
       investors: '"Warmsun Holding,  IDG Capital Partners"' },
     { name: 'United Imaging Healthcare',
       val: '5.00',
       date: '9/14/17',
       country: 'China',
       category: 'Healthcare',
       investors: '"China Life Insurance,  China Development Bank Capital,  CITIC Securities International"' },
     { name: 'GuaHao',
       val: '1.50',
       date: '9/22/15',
       country: 'China',
       category: 'Healthcare',
       investors: '"Tencent,  Morningside Group"' },
     { name: 'iCarbonX',
       val: '1.00',
       date: '4/12/16',
       country: 'China',
       category: 'Healthcare',
       investors: '"Tencent,  Vcanbio"' },
     { name: 'Liepin',
       val: '1.00',
       date: '6/28/16',
       country: 'China',
       category: 'HR & Workforce Management',
       investors: '"China Mobile,  Matrix Partners China,  Warbug Pincus"' },
     { name: 'DouyuTV',
       val: '1.51',
       date: '11/20/17',
       country: 'China',
       category: 'Internet Software & Services',
       investors: '"CMB International Capital,  Nanshan Capital,  Tencent Holdings"' },
     { name: 'NetEase Cloud Music',
       val: '1.16',
       date: '4/11/17',
       country: 'China',
       category: 'Internet Software & Services',
       investors: '"China International Capital Corporation,  Hunan TV & Broadcast Intermediary,  Shanghai Media Group"' },
     { name: 'Dt Dream',
       val: '1.00',
       date: '6/8/17',
       country: 'China',
       category: 'Internet Software & Services',
       investors: '"Alibaba Group,  China Everbright Investment Management,  Yinxinggu Capital"' },
     { name: 'Zhihu',
       val: '1.00',
       date: '1/12/17',
       country: 'China',
       category: 'Internet Software & Services',
       investors: '"Tencent Holdings,  Sinovation Ventures,  Qiming Venture Partners"' },
     { name: 'Apus Group',
       val: '1.00',
       date: '1/16/15',
       country: 'China',
       category: 'Mobile Software & Services',
       investors: '"Redpoint Ventures,  QiMing Venture Partners,  Chengwei Capital"' },
     { name: 'CAOCAO',
       val: '1.60',
       date: '1/17/18',
       country: 'China',
       category: 'On Demand',
       investors: '"People Electrical Appliance Group China,  Zhongrong International Trust"' },
     { name: 'Ofo',
       val: '1.00',
       date: '3/1/17',
       country: 'China',
       category: 'On Demand',
       investors: '"GSR Ventures,  Matrix Partners China,  Didi Chuxing"' },
     { name: 'Didi Chuxing',
       val: '56.00',
       date: '12/31/14',
       country: 'China',
       category: 'On-Demand',
       investors: '"Matrix Partners,  Tiger Global Management,  Softbank Corp., "' },
     { name: 'Ele.me',
       val: '5.50',
       date: '8/28/15',
       country: 'China',
       category: 'On-Demand',
       investors: '"Sequoia Capital China,  Alibaba Group,  Horizons Ventures"' },
     { name: 'Mobike',
       val: '3.00',
       date: '6/16/17',
       country: 'China',
       category: 'On-Demand',
       investors: '"Tencent Holdings,  Sequoia Capital China,  TPG Capital"' },
     { name: 'Huimin',
       val: '2.00',
       date: '9/5/16',
       country: 'China',
       category: 'On-Demand',
       investors: '"Zheshang Venture Capital,  GP Capital,  Western Capital Management"' },
     { name: 'e-shang Redwood',
       val: '2.80',
       date: '7/26/17',
       country: 'China',
       category: 'Real Estate',
       investors: '"SK Group,  GF Investments,  China Minsheng Banking Corp."' },
     { name: 'URWork',
       val: '1.30',
       date: '1/18/17',
       country: 'China',
       category: 'Real Estate',
       investors: '"Ant Financial Services Group,  Dahong Group,  Sequoia Capital China"' },
     { name: 'EasyHome',
       val: '5.70',
       date: '2/12/18',
       country: 'China',
       category: 'Retail',
       investors: '"Alibaba Group,  Boyu Capital,  Borui Capital"' },
     { name: 'UBTECH Robotics',
       val: '1.00',
       date: '7/26/16',
       country: 'China',
       category: 'Robotics',
       investors: '"CDH Investments,  Goldstone Investments,  Qiming Venture Partners"' },
     { name: 'Kuaishou',
       val: '3.00',
       date: '1/1/15',
       country: 'China',
       category: 'Social',
       investors: '"Morningside Venture Capital,  Sequoia Capital,  Baidu"' },
     { name: 'Yixia',
       val: '1.00',
       date: '11/24/15',
       country: 'China',
       category: 'Social',
       investors: '"Sequoia Capital China,  Sina Weibo,  Kleiner Perkins Caufield & Byers,  Redpoint Ventures"' },
     { name: 'Mogujie',
       val: '1.00',
       date: '6/6/14',
       country: 'China',
       category: 'Social',
       investors: '"IDG Capital Partners,  QiMing Venture Partners,  Banyan Capital"' },
     { name: 'YH Global',
       val: '1.00',
       date: '9/21/17',
       country: 'China',
       category: 'Supplychain/ logistics',
       investors: '"Co-Energy Finance,  Grandland"' } ],
  Colombia: 
   [ { name: 'LIfeMiles',
       val: '1.15',
       date: '7/13/15',
       country: 'Colombia',
       category: 'Business Products & Services',
       investors: 'Advent International' } ],
  'Czech Republic': 
   [ { name: 'AVAST Software',
       val: '1.00',
       date: '2/5/14',
       country: 'Czech Republic',
       category: 'Cybersecurity',
       investors: '"Summit Partners,  CVC Capital Partners"' } ],
  France: 
   [ { name: 'OVH',
       val: '1.10',
       date: '7/3/15',
       country: 'France',
       category: 'Big Data',
       investors: '"Kohlberg Kravis Roberts & Co., TowerBrook Capital Partners"' },
     { name: 'BlaBlaCar',
       val: '1.60',
       date: '9/16/15',
       country: 'France',
       category: 'On-Demand',
       investors: '"Accel Partners,  Index Ventures,  Insight Venture Partners"' } ],
  Germany: 
   [ { name: 'Auto1 Group',
       val: '3.54',
       date: '8/3/15',
       country: 'Germany',
       category: 'eCommerce/Marketplace',
       investors: '"Digital Sky Technologies,  Piton Capital,  DN Capital,  SoftBank Group"' },
     { name: 'Otto Bock HealthCare',
       val: '3.50',
       date: '6/24/17',
       country: 'Germany',
       category: 'Healthcare',
       investors: 'EQT Partners' },
     { name: 'CureVac',
       val: '1.65',
       date: '3/5/15',
       country: 'Germany',
       category: 'Healthcare',
       investors: '"Northview Ventures,  dievini Hopp BioTech Holding & Co.m Baillie Gifford & Co."' },
     { name: 'NuCom Group',
       val: '2.20',
       date: '2/22/18',
       country: 'Germany',
       category: 'Management & Strategy Consulting',
       investors: 'General Atlantic' } ],
  India: 
   [ { name: 'InMobi',
       val: '1.00',
       date: '12/2/14',
       country: 'India',
       category: 'Adtech',
       investors: '"Kleiner Perkins Caufield & Byers,  Softbank Corp.,  Sherpalo Ventures"' },
     { name: 'Flipkart',
       val: '11.60',
       date: '8/6/12',
       country: 'India',
       category: 'eCommerce/Marketplace',
       investors: '"Accel Partners,  SoftBank Group,  Iconiq Capital"' },
     { name: 'Snapdeal',
       val: '7.00',
       date: '5/21/14',
       country: 'India',
       category: 'eCommerce/Marketplace',
       investors: '"SoftBankGroup, Blackrock,  Alibaba Group"' },
     { name: 'Shopclues',
       val: '1.10',
       date: '1/12/16',
       country: 'India',
       category: 'eCommerce/Marketplace',
       investors: '"Nexus Venture Partners,  GIC Special Investments,  Tiger Global Management"' },
     { name: 'Quikr',
       val: '1.00',
       date: '4/7/15',
       country: 'India',
       category: 'eCommerce/Marketplace',
       investors: '"Brand Capital,  Tiger Global Management,  Kinnevik"' },
     { name: 'ReNew Power Ventures',
       val: '2.00',
       date: '2/14/17',
       country: 'India',
       category: 'Energy & Utilities',
       investors: '"Goldman Sachs,  JERA,  Asian Development Bank"' },
     { name: 'One97 Communications (operates Paytm)',
       val: '5.70',
       date: '5/12/15',
       country: 'India',
       category: 'Fintech',
       investors: '"Intel Capital,  Sapphire Ventures,  Alibaba Group"' },
     { name: 'Olacabs',
       val: '3.65',
       date: '10/27/14',
       country: 'India',
       category: 'On-demand',
       investors: '"Accel Partners,  SoftBank Group,  Sequoia Capital"' },
     { name: 'Hike',
       val: '1.40',
       date: '8/16/16',
       country: 'India',
       category: 'Social',
       investors: '"Foxconn,  Tiger Global management,  Tencent"' },
     { name: 'Zomato Media',
       val: '1.00',
       date: '4/10/15',
       country: 'India',
       category: 'Social',
       investors: '"Sequoia Capital,  VY Capital"' } ],
  Indonesia: 
   [ { name: 'Go-Jek',
       val: '1.80',
       date: '8/4/16',
       country: 'Indonesia',
       category: 'On-Demand',
       investors: '"Formation Group,  Sequoia Capital India,  Warburg Pincus"' },
     { name: 'Traveloka',
       val: '2.00',
       date: '7/28/17',
       country: 'Indonesia',
       category: 'TravelTech',
       investors: '"Global Founders Capital,  East Ventures,  Expedia Inc."' } ],
  Israel: 
   [ { name: 'OrCam Technologies',
       val: '1.00',
       date: '2/21/18',
       country: 'Israel',
       category: 'Consumer Electronics',
       investors: '"Intel Capital,  Aviv Venture Capital"' },
     { name: 'Infinidat',
       val: '1.60',
       date: '4/29/15',
       country: 'Israel',
       category: 'Hardware',
       investors: '"TPG Growth,  Goldman Sachs"' },
     { name: 'ironSource',
       val: '1.50',
       date: '8/11/14',
       country: 'Israel',
       category: 'Mobile Software & Services',
       investors: '"Access Industries,  Clal Industries and Investments"' } ],
  Japan: 
   [ { name: 'Mercari',
       val: '1.00',
       date: '3/2/16',
       country: 'Japan',
       category: 'eCommerce/Marketplace',
       investors: '"East Ventures,  Global Brain Corporation,  ITOCHU Technology Ventures"' } ],
  Luxembourg: 
   [ { name: 'Global Fashion Group',
       val: '1.10',
       date: '4/8/15',
       country: 'Luxembourg',
       category: 'eCommerce/Marketplace',
       investors: '"Access Industries,  Rocket Internet,  Tengelmann Ventures"' } ],
  Malta: 
   [ { name: 'VistaJet',
       val: '2.50',
       date: '8/23/17',
       country: 'Malta',
       category: 'On-demand',
       investors: 'Rhone Capital' } ],
  Netherlands: 
   [ { name: 'letgo',
       val: '1.00',
       date: '9/28/17',
       country: 'Netherlands',
       category: 'eCommerce/Marketplace',
       investors: '"Accel Partners,  FJ Labs,  Insight Venture Partners"' },
     { name: 'Adyen',
       val: '2.30',
       date: '12/16/14',
       country: 'Netherlands',
       category: 'Fintech',
       investors: '"Felicis Ventures,  Index Ventures,  Temasek Holdings"' } ],
  Nigeria: 
   [ { name: 'Africa Internet Group',
       val: '1.04',
       date: '2/8/16',
       country: 'Nigeria',
       category: 'eCommerce/Marketplace',
       investors: 'AXA' } ],
  Singapore: 
   [ { name: 'GrabTaxi',
       val: '6.00',
       date: '12/4/14',
       country: 'Singapore',
       category: 'On-Demand',
       investors: '"GGV Capital,  Vertex Venture Holdings,  Softbank Group"' } ],
  'South Africa': 
   [ { name: 'Promasidor Holdings',
       val: '1.58',
       date: '11/8/16',
       country: 'South Africa',
       category: 'Food and Beverage',
       investors: '"IFC,  Ajinomoto"' },
     { name: 'Cell C',
       val: '1.00',
       date: '8/8/17',
       country: 'South Africa',
       category: 'Telecommunications',
       investors: '"Blue Label Telecoms,  Net1 UEPS Technologies"' } ],
  'South Korea': 
   [ { name: 'L&P Cosmetic',
       val: '1.78',
       date: '4/28/17',
       country: 'South Korea',
       category: 'Beauty & grooming',
       investors: 'CDIB Capital' },
     { name: 'Coupang',
       val: '5.00',
       date: '5/28/14',
       country: 'South Korea',
       category: 'eCommerce/Marketplace',
       investors: '"Sequoia Capital,  Founder Collective,  Wellington Management"' },
     { name: 'Yello Mobile',
       val: '4.00',
       date: '11/11/14',
       country: 'South Korea',
       category: 'Mobile Software & Services',
       investors: 'Formation 8' } ],
  Sweden: 
   [ { name: 'Klarna',
       val: '2.50',
       date: '12/12/11',
       country: 'Sweden',
       category: 'Fintech',
       investors: '"Institutional Venture Partners,  Sequoia Capital,  General Atlantic"' },
     { name: 'Spotify',
       val: '8.53',
       date: '6/17/11',
       country: 'Sweden',
       category: 'Internet Software & Services',
       investors: '"Horizons Ventures,  Norwest Venture Partners,  Technology Crossover Ventures"' } ],
  Switzerland: 
   [ { name: 'Avaloq Group',
       val: '1.01',
       date: '3/22/17',
       country: 'Switzerland',
       category: 'Fintech',
       investors: 'Warbug Pincus' },
     { name: 'MindMaze',
       val: '1.00',
       date: '2/17/16',
       country: 'Switzerland',
       category: 'VR/AR',
       investors: 'Hinduja Group' } ],
  'United Arab Emirates': 
   [ { name: 'Careem Networks',
       val: '1.20',
       date: '12/18/16',
       country: 'United Arab Emirates',
       category: 'On Demand',
       investors: '"STC Ventures,  Al Tayyar Travel Group,  Wamda Capital"' } ],
  'United Kingdom': 
   [ { name: 'Improbable',
       val: '1.00',
       date: '5/12/17',
       country: 'United Kingdom',
       category: 'AR/VR',
       investors: '"Andreessen Horowitz,  SoftBank Group,  Temasek Holdings"' },
     { name: 'Global Switch',
       val: '6.02',
       date: '12/22/16',
       country: 'United Kingdom',
       category: 'Computer Hardware & Services',
       investors: '"Aviation Industry Corporation of China,  Essence Financial,  Jiangsu Sha Steel Group"' },
     { name: 'The Hut Group',
       val: '3.25',
       date: '8/13/17',
       country: 'United Kingdom',
       category: 'eCommerce',
       investors: '"Kohlberg Kravis Roberts & Co.,  Old Mutual Global Investors,  Artemis Investment Management"' },
     { name: 'Farfetch',
       val: '1.50',
       date: '3/4/15',
       country: 'United Kingdom',
       category: 'eCommerce/Marketplace',
       investors: '"Advent Venture Partners,  Index Ventures,  e.ventures"' },
     { name: 'BGL Group',
       val: '3.00',
       date: '11/24/17',
       country: 'United Kingdom',
       category: 'Fintech',
       investors: 'CPP Investment Board' },
     { name: 'TransferWise',
       val: '1.60',
       date: '1/26/15',
       country: 'United Kingdom',
       category: 'Fintech',
       investors: '"IA Ventures,  Index Ventures,  SV Angel"' },
     { name: 'ACORN OakNorth',
       val: '1.20',
       date: '10/12/17',
       country: 'United Kingdom',
       category: 'Fintech',
       investors: '"Clermont Group,  Coltrane Asset Management,  Toscafund Asset Management"' },
     { name: 'Funding Circle',
       val: '1.00',
       date: '4/23/15',
       country: 'United Kingdom',
       category: 'Fintech',
       investors: '"Accel Partners,  Index Ventures,  Ribbit Capital"' },
     { name: 'BrewDog',
       val: '1.15',
       date: '4/10/17',
       country: 'United Kingdom',
       category: 'Food & Beverages',
       investors: '"TSG Consumer Partners,  Crowdcube"' },
     { name: 'Oxford Nanopore Technologies',
       val: '1.55',
       date: '7/21/15',
       country: 'United Kingdom',
       category: 'Healthcare',
       investors: '"Illumina,  Invesco Perpetual,  IP Group"' },
     { name: 'benevolent.ai',
       val: '1.00',
       date: '6/2/15',
       country: 'United Kingdom',
       category: 'Healthcare',
       investors: 'Woodford Investment Management' },
     { name: 'Radius Payments Solutions',
       val: '1.07',
       date: '11/27/17',
       country: 'United Kingdom',
       category: 'Internet Software & Services',
       investors: 'Inflexion Private Equity' },
     { name: 'Deliveroo',
       val: '2.00',
       date: '9/25/17',
       country: 'United Kingdom',
       category: 'On-demand',
       investors: '"Accel Partners,  General Catalyst,  Index Ventures"' } ],
  'United States': 
   [ { name: 'Desktop Metal',
       val: '1.00',
       date: '7/17/17',
       country: 'United States',
       category: '3D Printing',
       investors: '"Australian Future Fund,  GE Ventures,  Data Collective"' },
     { name: 'AppLovin',
       val: '1.40',
       date: '1/1/17',
       country: 'United States',
       category: 'Adtech',
       investors: '"Orient Hontai Capital,  Webb Investment Network"' },
     { name: 'Appnexus',
       val: '1.20',
       date: '8/18/14',
       country: 'United States',
       category: 'Adtech',
       investors: '"Khosla Ventures,  Technology Crossover Ventures,  Tribeca Venture Partners"' },
     { name: 'Quanergy Systems',
       val: '1.59',
       date: '8/24/16',
       country: 'United States',
       category: 'Auto Tech',
       investors: '"Delphi Automotive,  Samsung Ventures,  Motus Ventures"' },
     { name: 'Zoox',
       val: '1.55',
       date: '5/27/16',
       country: 'United States',
       category: 'Auto Tech',
       investors: '"AID Partners,  Draper Fisher Jurvetson"' },
     { name: 'Palantir Technologies',
       val: '20.00',
       date: '5/5/11',
       country: 'United States',
       category: 'Big Data',
       investors: '"RRE Ventures,  Founders Fund,  In-Q-Tel"' },
     { name: 'Qualtrics',
       val: '2.50',
       date: '9/24/14',
       country: 'United States',
       category: 'Big Data',
       investors: '"Accel Partners,  Insight Venture Partners,  Sequoia Capital"' },
     { name: 'Uptake',
       val: '2.30',
       date: '10/27/15',
       country: 'United States',
       category: 'Big Data',
       investors: '"Revolution,  New Enterprise Associates,  Caterpillar"' },
     { name: 'Domo Technologies',
       val: '2.00',
       date: '4/8/15',
       country: 'United States',
       category: 'Big Data',
       investors: '"Institutional Venture Partners,  Benchmark Capital,  Founders Fund"' },
     { name: 'Insidesales.com',
       val: '1.50',
       date: '4/28/14',
       country: 'United States',
       category: 'Big Data',
       investors: '"Microsoft Ventures,  US Venture Partners,  Kleiner Perkins Caufield & Byers"' },
     { name: 'Mu Sigma',
       val: '1.50',
       date: '2/7/13',
       country: 'United States',
       category: 'Big Data',
       investors: '"Sequoia Capital,  General Atlantic"' },
     { name: 'Actifio',
       val: '1.10',
       date: '3/24/14',
       country: 'United States',
       category: 'Big Data',
       investors: '"Greylock Partners,  North Bridge Venture Partners,  Technology Crossover Ventures"' },
     { name: 'MarkLogic',
       val: '1.00',
       date: '5/12/15',
       country: 'United States',
       category: 'Big Data',
       investors: '"Sequoia Capital,  Tenaya Capital,  Northgate Capital"' },
     { name: 'Indigo Agriculture',
       val: '1.40',
       date: '9/26/17',
       country: 'United States',
       category: 'Biotech',
       investors: '"Activant Capital Group,  Alaska Permanent Fund,  Baillie Gifford & Co."' },
     { name: 'Ginkgo BioWorks',
       val: '1.00',
       date: '12/14/17',
       country: 'United States',
       category: 'Biotechnology',
       investors: '"Y Combinator,  Data Collective,  MassVentures"' },
     { name: 'MedMen',
       val: '1.00',
       date: '2/6/18',
       country: 'United States',
       category: 'Cannabis',
       investors: '"Captor Capital,  N Squared Management"' },
     { name: 'Rubicon Global',
       val: '1.00',
       date: '8/25/17',
       country: 'United States',
       category: 'Cleantech',
       investors: '"Goldman Sachs,  Leonardo DiCaprio,  Promecap"' },
     { name: 'Kendra Scott Jewelry',
       val: '1.00',
       date: '12/21/16',
       country: 'United States',
       category: 'Clothing & Accessories',
       investors: '"Berkshire Partners,  Norwest Venture Partners"' },
     { name: 'Supreme',
       val: '1.00',
       date: '10/9/17',
       country: 'United States',
       category: 'Clothing & Accessories',
       investors: 'The Carlyle Group' },
     { name: 'Katerra',
       val: '1.00',
       date: '4/13/17',
       country: 'United States',
       category: 'Construction Tech',
       investors: '"Foxconn Technology Company,  Khosla Ventures,  Moore Capital Management"' },
     { name: 'Procore Technologies',
       val: '1.00',
       date: '12/8/16',
       country: 'United States',
       category: 'Construction Tech',
       investors: '"Bessemer Venture Partners,  O\'Connor Ventures,  Iconiq Capital"' },
     { name: 'Tanium',
       val: '3.75',
       date: '3/31/15',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"Andreessen Horowitz,  Nor-Cal Invest,  TPG Growth"' },
     { name: 'CloudFlare',
       val: '1.00',
       date: '12/1/12',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"New Enterprise Associates,  Pelion Venture Partners,  Union Square Ventures"' },
     { name: 'Lookout',
       val: '1.00',
       date: '8/13/14',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"Accel Partners,  Greylock Partners,  Lowercase Capital"' },
     { name: 'Illumio',
       val: '1.00',
       date: '4/14/14',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"Data Collective,  Formation 8,  General Catalyst Partners"' },
     { name: 'CrowdStrike',
       val: '1.00',
       date: '5/17/17',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"Warbug Pincus,  capitalG,  Accel Partners"' },
     { name: 'Cylance',
       val: '1.00',
       date: '6/8/16',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"Khosla Ventures,  Fairhaven Capital,  In-Q-Tel"' },
     { name: 'Zscaler',
       val: '1.00',
       date: '8/3/15',
       country: 'United States',
       category: 'Cybersecurity',
       investors: '"capitalG,  EMC Ventures,  Lightspeed Venture Partners"' },
     { name: 'Duo Security',
       val: '1.17',
       date: '10/18/17',
       country: 'United States',
       category: 'Cybsersecurity',
       investors: '"Meritech Capital,  Lead Edge Capital,  Benchmark"' },
     { name: 'HeartFlow',
       val: '1.19',
       date: '12/4/17',
       country: 'United States',
       category: 'Digital Health',
       investors: '"BlueCross BlueShield Venture Partners,  US Venture Partners"' },
     { name: 'Particle',
       val: '1.00',
       date: '10/17/17',
       country: 'United States',
       category: 'Digital Media',
       investors: 'Phoenix New Media' },
     { name: 'Airbnb',
       val: '29.30',
       date: '7/26/11',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"General Catalyst Partners,  Andreessen Horowitz,  ENIAC Ventures"' },
     { name: 'Fanatics',
       val: '4.50',
       date: '6/6/12',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"SoftBank Group,  Andreessen Horowitz,  Temasek Holdings"' },
     { name: 'Houzz',
       val: '4.00',
       date: '9/30/14',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"New Enterprise Associates,  Sequoia Capital,  Comcast Ventures"' },
     { name: 'ContextLogic (dba. Wish)',
       val: '3.00',
       date: '5/18/15',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"Founders Fund,  GGV Capital,  Digital Sky Technologies"' },
     { name: 'Thumbtack',
       val: '1.20',
       date: '9/29/15',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"Tiger Global,  Sequoia Capital,  Google Capital"' },
     { name: 'Warby Parker',
       val: '1.20',
       date: '4/30/15',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"BoxGroup,  Felicis Ventures,  First Round Capital"' },
     { name: 'OfferUp',
       val: '1.20',
       date: '9/8/16',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"Andreessen Horowitz,  GGV Capital,  T. Rowe Price"' },
     { name: 'TechStyle Fashion Group',
       val: '1.00',
       date: '8/29/14',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"Matrix Partners,  Passport Capital,  Rho Ventures"' },
     { name: 'Eventbrite',
       val: '1.00',
       date: '3/13/14',
       country: 'United States',
       category: 'eCommerce/Marketplace',
       investors: '"Sequoia Capital,  Tiger Global Management,  SV Angel"' },
     { name: 'Age of Learning',
       val: '1.00',
       date: '5/3/16',
       country: 'United States',
       category: 'Edtech',
       investors: 'Iconiq Capital' },
     { name: 'STX Entertainment',
       val: '1.50',
       date: '8/10/16',
       country: 'United States',
       category: 'Entertainment',
       investors: '"Tencent,  TPG Growth,  Hony Capital"' },
     { name: 'WeWork',
       val: '20.00',
       date: '2/3/14',
       country: 'United States',
       category: 'Facilities',
       investors: '"T. Rowe Price,  Benchmark Capital,  SoftBank Group"' },
     { name: 'Mozido',
       val: '2.39',
       date: '10/22/14',
       country: 'United States',
       category: 'Fin Tech',
       investors: '"Wellington Management,  TomorrowVentures,  Mastercard Worldwide"' },
     { name: 'Stripe',
       val: '9.20',
       date: '1/23/14',
       country: 'United States',
       category: 'Fintech',
       investors: '"Khosla Ventures,  Lowercase Capital,  capitalG"' },
     { name: 'Robinhood',
       val: '5.60',
       date: '4/26/17',
       country: 'United States',
       category: 'Fintech',
       investors: '"Google Ventures,  Andreessen Horowitz,  DST Global"' },
     { name: 'Social Finance',
       val: '4.00',
       date: '2/3/15',
       country: 'United States',
       category: 'Fintech',
       investors: '"Baseline Ventures,  DCM Ventures,  Institutional Venture Partners"' },
     { name: 'Credit Karma',
       val: '3.50',
       date: '9/29/14',
       country: 'United States',
       category: 'Fintech',
       investors: '"Felicis Ventures,  SV Angel,  Founders Fund"' },
     { name: 'Zenefits',
       val: '2.00',
       date: '5/6/15',
       country: 'United States',
       category: 'Fintech',
       investors: '"SV Angel, ÊInstitutional Venture Partners,  Venrock"' },
     { name: 'Greensky',
       val: '2.00',
       date: '10/22/15',
       country: 'United States',
       category: 'Fintech',
       investors: '"DST Global,  QED Investors,  TPG Capital"' },
     { name: 'Avant',
       val: '2.00',
       date: '9/30/15',
       country: 'United States',
       category: 'Fintech',
       investors: '"RRE Ventures,  Tiger Global,  August Capital"' },
     { name: 'Affirm',
       val: '2.00',
       date: '12/11/17',
       country: 'United States',
       category: 'Fintech',
       investors: '"Andreessen Horowitz,  Khosla Ventures,  Singapore Wealth Fund"' },
     { name: 'Coinbase',
       val: '1.60',
       date: '8/10/17',
       country: 'United States',
       category: 'Fintech',
       investors: '"Y Combinator,  Union Square Ventures,  DFJ Growth"' },
     { name: 'AvidXchange',
       val: '1.40',
       date: '6/8/17',
       country: 'United States',
       category: 'Fintech',
       investors: '"Temasek Holdings,  Charlotte Angel Partners,  TPG Growth"' },
     { name: 'Kabbage',
       val: '1.00',
       date: '10/14/15',
       country: 'United States',
       category: 'Fintech',
       investors: '"BlueRun Ventures,  SV Angel,  Mohr Davidow Ventures"' },
     { name: 'Gusto',
       val: '1.00',
       date: '12/18/15',
       country: 'United States',
       category: 'Fintech',
       investors: '"General Catalyst Partners,  Google Ventures,  Kleiner Perkins Caufield & Byers"' },
     { name: 'Symphony Communication Services Holdings',
       val: '1.00',
       date: '5/16/17',
       country: 'United States',
       category: 'Fintech',
       investors: '"BNP Paribas,  Goldman Sachs,  Google"' },
     { name: 'Peloton Interactive',
       val: '1.30',
       date: '5/24/17',
       country: 'United States',
       category: 'Fitness',
       investors: '"True Ventures,  Tiger Global Management,  L Catterton"' },
     { name: 'DoorDash',
       val: '1.40',
       date: '3/1/18',
       country: 'United States',
       category: 'Food Delivery',
       investors: '"Softbank Group,  Sequoia Capital,  Khosla Ventures"' },
     { name: 'Unity Technologies',
       val: '2.60',
       date: '7/13/16',
       country: 'United States',
       category: 'Gaming',
       investors: '"Sequoia Capital,  iGlobe Partners,  DFJ Growth"' },
     { name: 'GRAIL',
       val: '2.46',
       date: '3/1/17',
       country: 'United States',
       category: 'Genomics',
       investors: '"Kleiner Perkins Caufield & Byers,  Amazon,  Merck & Co."' },
     { name: 'Bloom Energy',
       val: '2.70',
       date: '3/6/09',
       country: 'United States',
       category: 'Greentech',
       investors: '"Kleiner Perkins Caufield & Byers,  ATEL Ventures,  DAG Ventures"' },
     { name: 'Carbon3D',
       val: '1.70',
       date: '12/20/17',
       country: 'United States',
       category: 'Hardware',
       investors: '"Google Ventures,  Sequoia Capital,  Wakefield Group"' },
     { name: 'Intarcia Therapeutics',
       val: '5.50',
       date: '4/1/14',
       country: 'United States',
       category: 'Healthcare',
       investors: '"New Enterprise Associates,  New Leaf Venture Partners,  Charter Venture Capital"' },
     { name: 'Outcome Health',
       val: '5.00',
       date: '5/31/17',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Goldman Sachs,  capitalG,  Pritzker Group Venture Capital"' },
     { name: 'Moderna',
       val: '3.00',
       date: '12/19/14',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Flagship Ventures,  Invus Group,  Wellington Management"' },
     { name: 'Oscar Health Insurance Co.',
       val: '2.70',
       date: '4/20/15',
       country: 'United States',
       category: 'Healthcare',
       investors: '"BoxGroup,  Formation8,  Khosla Ventures"' },
     { name: 'Zocdoc',
       val: '1.80',
       date: '8/20/15',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Founders Fund,  Khosla Ventures,  Goldman Sachs"' },
     { name: '23andMe',
       val: '1.50',
       date: '7/3/15',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Google Ventures,  New Enterprise Associates,  MPM Capital"' },
     { name: 'Clover Health',
       val: '1.20',
       date: '5/10/17',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Google Ventures,  Sequoia Capital,  First Round Capital"' },
     { name: 'Human Longevity',
       val: '1.20',
       date: '4/5/16',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Celgene,  GE Ventures,  Draper Fisher Jurvetson"' },
     { name: 'Proteus Digital Health',
       val: '1.10',
       date: '6/2/14',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Novartis,  Essex Woodlands,  The Carlyle Group"' },
     { name: 'Adaptive Biotechnologies',
       val: '1.00',
       date: '1/8/15',
       country: 'United States',
       category: 'Healthcare',
       investors: '"Illumina,  Celgene,  Casdin Capital"' },
     { name: 'Dropbox',
       val: '10.00',
       date: '10/5/11',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Accel Partners,  Greylock Partners,  Index Ventures"' },
     { name: 'Infor',
       val: '10.00',
       date: '11/16/16',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Blackstone Group,  Koch Industries"' },
     { name: 'Slack Technologies',
       val: '5.10',
       date: '10/31/14',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Google Ventures,  Institutional Venture Partners,  Index Ventures"' },
     { name: 'DocuSign',
       val: '3.00',
       date: '3/4/14',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Accel Partners,  Bessemer Venture Partners,  Ignition Partners"' },
     { name: 'Github',
       val: '2.00',
       date: '7/30/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Sequoia Capital,  Thrive Capital,  SV Angel"' },
     { name: 'Quora',
       val: '1.80',
       date: '4/21/17',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Y Combinator,  Matrix Partners,  Benchmark"' },
     { name: 'Sprinklr',
       val: '1.80',
       date: '3/31/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Azure Capital Partners,  Battery Ventures,  Intel Capital"' },
     { name: 'Apttus',
       val: '1.75',
       date: '9/1/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Iconiq Capital,  K1 Capital,  Salesforce Ventures"' },
     { name: 'Squarespace',
       val: '1.70',
       date: '12/14/17',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"General Atlantic,  Index Ventures,  Accel Partners"' },
     { name: 'Afiniti',
       val: '1.60',
       date: '4/14/17',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: 'GAM Holding' },
     { name: 'Snowflake Computing',
       val: '1.50',
       date: '7/3/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Redpoint Ventures, Iconiq Capital,  Madrona Venture Group"' },
     { name: 'Anaplan',
       val: '1.40',
       date: '1/14/16',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Shasta Ventures,  Granite Ventures,  DFJ Growth Fund"' },
     { name: 'DraftKings',
       val: '1.35',
       date: '7/26/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Accomplice,  GGV Capital,  Redpoint Ventures"' },
     { name: 'Rubrik',
       val: '1.30',
       date: '4/28/17',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Greylock Partners,  Lightspeed Venture Partners,  Khosla Ventures"' },
     { name: 'Zeta Interactive',
       val: '1.30',
       date: '7/15/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"GSO Capital Partners,  Franklin Square"' },
     { name: 'Docker',
       val: '1.30',
       date: '4/14/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Greylock Partners,  Lightspeed Venture Partners,  Lowercase Capital"' },
     { name: 'Ten-X',
       val: '1.20',
       date: '3/5/14',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Stone Point Capital,  Google Capital"' },
     { name: 'Automattic',
       val: '1.16',
       date: '5/27/13',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Insight Venture Partners,  Lowercase Capital,  Polaris Partners"' },
     { name: 'AppDirect',
       val: '1.04',
       date: '10/7/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Mithril,  iNovia Capital,  Foundry Group"' },
     { name: 'Pluralsight',
       val: '1.00',
       date: '12/13/16',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Iconiq Capital,  Insight Venture Partners,  Sorenson Capital"' },
     { name: 'Medallia',
       val: '1.00',
       date: '7/21/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: 'Sequoia Capital' },
     { name: 'Fanduel',
       val: '1.00',
       date: '7/14/15',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Pentech Ventures,  Bullpen Capital,  KKR"' },
     { name: 'Glassdoor',
       val: '1.00',
       date: '6/3/16',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"T. Rowe Price,  Battery Ventures,  Tiger Global Management"' },
     { name: 'SMS Assist',
       val: '1.00',
       date: '6/13/16',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Goldman Sachs,  Insights Venture Partners,  Pritzker Group Venture Capital"' },
     { name: 'Zoom Communications',
       val: '1.00',
       date: '1/17/17',
       country: 'United States',
       category: 'Internet Software & Services',
       investors: '"Sequoia Capital,  Qualcomm Ventures,  Emergence Capital Partners"' },
     { name: 'C3 IoT',
       val: '1.40',
       date: '3/2/17',
       country: 'United States',
       category: 'IoT',
       investors: '"Makena Capital Management,  TPG Growth,  Breyer Capital"' },
     { name: 'Vice Media',
       val: '5.70',
       date: '8/17/13',
       country: 'United States',
       category: 'Media',
       investors: '"Technology Crossover Ventures,  A&E Television Networks"' },
     { name: 'Buzzfeed',
       val: '1.70',
       date: '8/18/15',
       country: 'United States',
       category: 'Media',
       investors: '"SV Angel,  RRE Ventures,  New Enterprise Associates"' },
     { name: 'Vox Media',
       val: '1.00',
       date: '8/12/15',
       country: 'United States',
       category: 'Media',
       investors: '"Accel Partners,  Comcast Ventures,  General Atlantic"' },
     { name: 'Uber',
       val: '68.00',
       date: '8/23/13',
       country: 'United States',
       category: 'On-Demand',
       investors: '"Lowercase Capital,  Benchmark Capital,  Google Ventures"' },
     { name: 'Lyft',
       val: '11.50',
       date: '3/12/15',
       country: 'United States',
       category: 'On-Demand',
       investors: '"Founders Fund,  Mayfield Fund,  capitalG"' },
     { name: 'Instacart',
       val: '4.20',
       date: '12/30/14',
       country: 'United States',
       category: 'On-Demand',
       investors: '"Khosla Ventures,  Kleiner Perkins Caufield & Byers,  Collaborative Fund"' },
     { name: 'SpaceX',
       val: '21.50',
       date: '12/1/12',
       country: 'United States',
       category: 'Other Transportation',
       investors: '"Founders Fund,  Draper Fisher Jurvetson,  Rothenberg Ventures"' },
     { name: 'Compass',
       val: '2.20',
       date: '8/31/16',
       country: 'United States',
       category: 'Real Estate',
       investors: '"Founders Fund,  Thrive Capital,  Wellington Management"' },
     { name: 'OpenDoor Labs',
       val: '1.00',
       date: '11/30/16',
       country: 'United States',
       category: 'Real Estate',
       investors: '"Norwest Venture Partners,  New Enterprise Associates,  Khosla Ventures"' },
     { name: 'UiPath',
       val: '1.10',
       date: '3/2/18',
       country: 'United States',
       category: 'Robotic Process Automation',
       investors: '"Accel Partners,  capitalG,  Earlybrid Venture Capital,  Kleiner Perkins Caufield & Byers"' },
     { name: 'Pinterest',
       val: '12.30',
       date: '5/19/12',
       country: 'United States',
       category: 'Social',
       investors: '"Andreessen Horowitz,  Bessemer Venture Partners,  Firstmark Capital"' },
     { name: 'reddit',
       val: '1.80',
       date: '7/31/17',
       country: 'United States',
       category: 'Social',
       investors: '"Y Combinator,  Sequoia Capital,  Coatue Management"' },
     { name: 'Nextdoor',
       val: '1.50',
       date: '3/4/15',
       country: 'United States',
       category: 'Social',
       investors: '"Benchmark Capital,  DAG Ventures,  Insight Venture Partners"' },
     { name: 'TangoMe',
       val: '1.10',
       date: '3/20/14',
       country: 'United States',
       category: 'Social',
       investors: '"Draper Fisher Jurtson,  Qualcomm Ventures,  Alibaba Group"' },
     { name: 'Rocket Lab',
       val: '1.00',
       date: '3/21/17',
       country: 'United States',
       category: 'SpaceTech',
       investors: '"Lockheed Martin,  Khosla Ventures,  Bessemer Venture Partners"' },
     { name: 'JetSmarter',
       val: '1.50',
       date: '12/12/16',
       country: 'United States',
       category: 'TravelTech',
       investors: '"Jay-Z,  Saudi Royal Family,  Jet Edge"' },
     { name: 'Magic Leap',
       val: '4.98',
       date: '10/21/14',
       country: 'United States',
       category: 'VR/AR',
       investors: '"Obvious Ventures,  Qualcomm Ventures,  Andreessen Horowitz"' } ] 
     }

}